### ISSUE TITLE
Please consider publishing a new release

### ISSUE THREAD

**Issue by complexspaces** [jneem/range-map#2]
Hey there 👋. While looking at integrating the [minidump](https://crates.io/crates/minidump) crate into our codebase, we found that it was bringing in both versions `0.1` and `0.2` of `num-traits`. This is non-ideal since it ends up causing a duplicate dependency in the tree. The cause of this was that it uses `0.2` itself but `range-map` uses `0.1`.

I noticed that you mentioned not publishing anything yet in #1, but the reason was unclear. Was this just due to lack of feedback in the issue or was there another blocker? Do you have the time to take a look at this again and see if its reasonable to finally publish an update?

**Comment by jneem** [comment]
Honestly, it was so long ago that I don't remember anymore :shrug:. Probably I just forgot because I never got a reply. But sure, I have no objection to publishing a new release. I can probably manage it today or tomorrow.

**Comment by jneem** [comment]
Ok, I've published 0.2.0.

**Comment by complexspaces** [comment]
Thank you a bunch for that.
